### ISSUE TITLE
useSSL: true, does not use wss:// 

### ISSUE THREAD

**Issue by ReallyCrazyChris** [kaandesu/vue-paho-mqtt#63]
Thie option useSSL true is not using wss.// 

These Options:
      MqttOptions: {
        host: "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx.s2.eu.hivemq.cloud",
        port: 8884,
        clientId: `MyID-${Math.random() * 9999}`,
        mainTopic: "mqtt",
        username: "test1",
        password: "TestPass",
        useSSL: true,
      },

Result in : 
WebSocket connection to 'ws://xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx.s2.eu.hivemq.cloud:8884/mqtt' failed:

Should be: 
WebSocket connection to 'wss://xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx.s2.eu.hivemq.cloud:8884/mqtt' 

Thanks

**Comment by kaandesu** [comment]
Hello, were you trying this on a deployed site with an https connection or on a localhost (http)? For wss, https should be used. In paho-mqtt, it tries to connect to ws:// if it didn't work then it tries to connect to wss:// and it only tries that when the web app is deployed on https. If you confirm this error happened while in https, we'll check it these days.

**Comment by ReallyCrazyChris** [comment]
I am developing in Quasar .. on a localhost (http).  I try to corret this

**Comment by ReallyCrazyChris** [comment]
Updated Quasar to serve as https but wss.// is still not coming:

vue-paho-mqtt.js:429 Mixed Content: The page at 'https://localhost:8080/#/' was loaded over HTTPS, but attempted to connect to the insecure WebSocket endpoint 'ws://xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx.s2.eu.hivemq.cloud:8884/mqtt'. This request has been blocked; this endpoint must be available over WSS.

**Comment by EgeOnder** [comment]
> Updated Quasar to serve as https but wss.// is still not coming:
> 
> vue-paho-mqtt.js:429 Mixed Content: The page at 'https://localhost:8080/#/' was loaded over HTTPS, but attempted to connect to the insecure WebSocket endpoint 'ws://xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx.s2.eu.hivemq.cloud:8884/mqtt'. This request has been blocked; this endpoint must be available over WSS.

Hey 👋 have you tried to deploy your application to cloud and securing it with SSL/TLS? I don't know if it would work with `localhost` trying to connect to a secure WebSocket.

**Comment by ReallyCrazyChris** [comment]
Ok deployed to webserver : https://reallycrazychris.github.io 

error "Failed to construct 'WebSocket': An insecure WebSocket connection may not be initiated from a page loaded over HTTPS."

src:  https://github.com/ReallyCrazyChris/RoboBuoyApp/blob/master/src/boot/mqtt.js

**Comment by xiaokuili** [comment]
I alse meet this error. 
url: https://brain-invest-xxxxx/enterpriseCheck/search
err:
index-ad92ba17.js:5020 Mixed Content: The page at 'https://brain-invexxxi.net/enterpriseCheck/search' was loaded over HTTPS, but attempted to connect to the insecure WebSocket endpoint 'ws://emxxxxm:443/mqtt'. This request has been blocked; this endpoint must be available over WSS.

**Comment by kaandesu** [comment]
Hello, thanks for contacting, we are going to work on the issue on the following days. 🙏

**Comment by kaandesu** [comment]
Hello people!  Version v0.4.0 of vue-paho-mqtt has just been published, hopefully fixing this issue. Can you install the latest package from npm and try again? Please let us know if it is fixed or if the problem still remains for you. 
It passed our tests for the brokers we've been using, and hopefully fixes for your broker of choice. _(Again reminding you to test on https if http didn't work.)_

**Comment by STM3900** [comment]
Hello ! I'm pleased to announce that everything is working on my end! I've hosted my site on Netifly and it connects to my broker using SSL
Thank you very much for your reactivity and your help!

**Comment by kaandesu** [comment]
Fixed with PR #65
