### ISSUE TITLE
AMQJS0010E WebSocket is not supported by this browser when launching app

### ISSUE THREAD

**Issue by STM3900** [kaandesu/vue-paho-mqtt#64]
I've just installed the package on a new nuxt3 application and I get this error on launch
![image](https://github.com/kaandesu/vue-paho-mqtt/assets/44432694/5f34bc0b-5751-429a-a943-4cbaa05d57c5)
I use chrome as my browser, so it accepts websockets, so I don't really understand

**Comment by kaandesu** [comment]
Hello, may I ask you what steps you took to install the package to the nuxt3? 
To test I created a nuxt3 project and added the https://github.com/kaandesu/vue-paho-mqtt#nuxt3-nuxt-plugins to a file under the 'plugins' folder, and I didn't have any problem with Chrome.

If this happened after those steps, you can try installing ws  as ```npm i ws@^3.3.1```
and adding that to a file ```global.WebSocket = require('ws');``` [source](https://github.com/awslabs/aws-mobile-appsync-sdk-js/issues/294#issuecomment-439499091)

**Comment by STM3900** [comment]
Same as you, apparently

I created my nuxt3 project with `npx nuxi@latest init mqtt-test`
then I installed the dependencies with `npm install`
then I installed paho-mqtt with `npm install vue-paho-mqtt`, then I created a `plugins` folder in which I created the file `paho-mqtt.js` in which I put this code :

```
import { createPahoMqttPlugin } from 'vue-paho-mqtt';
export default defineNuxtPlugin({
  name: 'vue-paho-mqtt',
  enforce: 'pre',
  async setup(nuxtApp) {
    nuxtApp.vueApp.use(
      createPahoMqttPlugin({
        PluginOptions: {
          autoConnect: true,
          showNotifications: true,
        },
        MqttOptions: {
          host: 'localhost',
          port: 9001,
          clientId: `MyID-${Math.random() * 9999}`,
          mainTopic: 'MAIN',
        },
      }),
    );
  },
  hooks: {
    'app:created'() {
      const nuxtApp = useNuxtApp();
    },
  },
});
```

and then I launched my app with npm run dev, and I get the error

-----

I tried to install ws but it doesn't seem to have worked. I put `global.WebSocket = require('ws');` at the top of the `paho-mqtt.js` file but I don't know if that's what I should do (I apologize, I'm still a beginner).

btw my node version is v18.17.1, and I had the same problem with an older version

**Comment by kaandesu** [comment]
Hello, sorry for the late response, i did everything you said, and i got the same error now. And after some trials, I noticed in the 'nuxt.config.ts' if I set ssr to false, it starts working for me. So on SPA it worked.
```js
// https://nuxt.com/docs/api/configuration/nuxt-config
export default defineNuxtConfig({
  devtools: { enabled: true },
  ssr: false,
})
```
and just to note, i used  'npm create vite@latest' to create my nuxt project, as i selected nuxt in during the creation, and i didn't have problem even in the ssr was true after that. 
But regardless, for your case, 'ssr:false' should work.

**Comment by STM3900** [comment]
Thank you very much for your reply, it was indeed ssr that I had to disable!

However, it's now a bit off topic from this issue, but I still have an error concerning the connection to my mqtt broker.
I've entered my connection information in the plugin, and I get this error:

![image](https://github.com/kaandesu/vue-paho-mqtt/assets/44432694/05b2a170-35b3-4e13-b477-33fdfbc634fb)

What makes me a bit confused is that I really have the impression that I've correctly configured the plugin, and that my connection information is correct (I've tested it identically on the https://www.hivemq.com/demos/websocket-client/ site and everything works).

This is what my plugin file config looks like : 

```
//plugins/mqtt.js
import { createPahoMqttPlugin } from 'vue-paho-mqtt';
export default defineNuxtPlugin({
  name: 'vue-paho-mqtt',
  enforce: 'pre',
  async setup(nuxtApp) {
    nuxtApp.vueApp.use(
      createPahoMqttPlugin({
        PluginOptions: {
          autoConnect: false,
          showNotifications: true,
        },
        MqttOptions: {
          host: 'myhost.com',
          port: 8083,
          username: "username",
          password: "password",
          clientId: `myclientid`,
          useSSL: true,
          enableMainTopic: false
        },
      }),
    );
  },
  hooks: {
    'app:created'() {
      const nuxtApp = useNuxtApp();
    },
  },
});
```

Thanks in advance for your reply!

**Comment by kaandesu** [comment]
Hi there, I wanted to ask if you were testing this on localhost. To connect to a broker that is not is not running locally you generally need WSS connection instead of WS. And so you need HTTPS protocol, and localhost runs on http. So you might want to deploy your webapp to test it (domain with a STL or TLS cerficate so its https).

**Comment by STM3900** [comment]
Yes indeed, I was developing locally, and I actually need a WSS connection to connect to my broker, thank you very much I had no idea haha

I deployed my application on netifly and got this error:
![image](https://github.com/kaandesu/vue-paho-mqtt/assets/44432694/92e9d881-79cb-442d-95bc-3972e3e27203)

And it matches the issue you mentioned so I'll wait for updates on it, thanks again!

**Comment by kaandesu** [comment]
> Hello people!  Version v0.4.0 of vue-paho-mqtt has just been published, hopefully fixing this issue. Can you install the > latest package from npm and try again? Please let us know if it is fixed or if the problem still remains for you. 
> It passed our tests for the brokers we've been using, and hopefully fixes for your broker of choice. _(Again reminding you > to test on https if http didn't work.)_

update on issue 63
