### ISSUE TITLE
problem with version 0.5

### ISSUE THREAD

**Issue by GJean** [kaandesu/vue-paho-mqtt#77]
Hello,

I just updated the dependency in my VueJS project to version 0.5 but the code I added for the username/password and the path are not present in it, it's really very weird. 

![Capture d’écran du 2024-04-08 23-05-32](https://github.com/kaandesu/vue-paho-mqtt/assets/516719/35352404-4d81-45f9-aeb0-40c9177e7367)

![Capture d’écran du 2024-04-08 23-05-53](https://github.com/kaandesu/vue-paho-mqtt/assets/516719/6d075081-522a-4eb0-93f7-f27710af44a0)

**Comment by EgeOnder** [comment]
I HAVE FIGURED OUT THIS STUPID MISTAKE

will fix soon, sorry
