### ISSUE TITLE
Client always tries wss connection, even with useSSL: false

### ISSUE THREAD

**Issue by andypotato** [kaandesu/vue-paho-mqtt#85]
I am creating the plugin with the following options:

```
createPahoMqttPlugin({
    PluginOptions: {
        autoConnect: true,
        showNotifications: false,
    },
    MqttOptions: {
        host: "192.168.2.80",
        port: 9001,
        clientId: "CL1",
        useSSL: false,
        mainTopic: 'MAIN',
    },
})
```

This will result in the following error on the console:
```
WebSocket connection to 'wss://192.168.2.80:9001/mqtt' failed: Error in connection establishment: net::ERR_SSL_PROTOCOL_ERROR
```

The connection will still succeed as there will automatically be a second connection attempt using `ws` protocol which works just fine.

Is it possible to remove the first connection attempt to `wss` if `useSSL` is explicitly set to `false` ?

**Comment by kaandesu** [comment]
Fixed in the 0.6.4 version, let us know if the issue persists.  
_reinstall the package to see the effects_
