### ISSUE TITLE
[Bug] Uncaught (in promise) undefined

### ISSUE THREAD

**Issue by andypotato** [kaandesu/vue-paho-mqtt#89]
I'm manually connecting to a MQTT broker using the following code:

```
try {
  const mqttResult = await this.$mqtt.connect({
    onConnectionLost: (error) => {
      console.log("Connection lost");
    },
  });
  return mqttResult
}
catch(e) {
  console.error("MQTT ERROR", e);
  return false;
}
```

Next, to test the reconnection feature, I am shutting down the MQTT broker. This will trigger the `onConnectionLost` handler as expected. I can see the following output on the console:

```
mqtt disconnected            vue-paho-mqtt.js?7fbb:2404
mqtt connection lost         vue-paho-mqtt.js?7fbb:2404
Connection lost              Menu.vue?c578:46
```

As expected the reconnection will trigger after 5 seconds (MQTT broker is still down):
```
WebSocket connection to 'ws://192.168.2.88:9001/mqtt' failed: Error in connection establishment: net::ERR_CONNECTION_TIMED_OUT
```

Now I'm waiting for another 20 seconds or so, then another error will appear on the console:

```
mqtt failed to connect              vue-paho-mqtt.js?7fbb:2408 
Uncaught (in promise) undefined     vue-paho-mqtt.js?7fbb:2406 
```

This `Uncaught` error will cause my Vue application to crash with the `Unknown promise rejection reason` error.

**Comment by andypotato** [comment]
Some more testing that I performed:

This error is triggered both on initial connects and reconnects. The root cause seems to be inside `connectClient.ts`, specifically in `onFailure()`

There are multiple issues with "onFailure":

1) `reject()` should be called with an argument, for example `false`. It should not be rejected as `undefined`

2) I believe the code at some point calls the `onFailure()` method, but does not handle the rejection.

3) The rejection happens much later than the actual connection failure. For example, I try to connect to a non-existing MQTT broker. I will see the following error on the console after about 5 seconds:

```
WebSocket connection to 'ws://192.168.2.88:9001/mqtt' failed: Error in connection establishment: net::ERR_CONNECTION_TIMED_OUT

vue-paho-mqtt.js?7fbb:1776 
```

However the actual onFailure() rejection is only triggered about 20 seconds later

**Comment by andypotato** [comment]
Digging deeper into this issue:

If you check `onConnectionLost.ts` the following code triggers the reconnection:

```
await connectClient();
```

However this code does not handle any rejection or error, therefore the error will bubble up to the application

As a workaround you could wrap it in a try / catch block.

However I believe the root cause of this error is the library not handling the websocket connection failure as seen in my last comment.

**Comment by kaandesu** [comment]
> However I believe the root cause of this error is the library not handling the websocket connection failure as seen in my last comment.

i also think this.

> As a workaround you could wrap it in a try / catch block.

for now i created another [branch](https://github.com/kaandesu/vue-paho-mqtt/tree/fix/uncaught-promise) just doing that, but i'll further investigate.

for today, i'll won't be available for a while
@EgeOnder can you check this issue, maybe on the branch mentioned? issue is reproducible on the live demo

**Comment by kaandesu** [comment]
version [0.6.5](https://www.npmjs.com/package/vue-paho-mqtt) is published, @andypotato please let us know if its fixed for you, again thanks for pointing this out with the issue

**Comment by andypotato** [comment]
Thank you guys very much for that quick fix!

I can confirm that this fix prevents the application from crashing. Just one more thing to consider: With the fix in place, the library will try to reconnect to the MQTT broker ONCE. If the reconnect attempt fails, there will be no further reconnects.

This may be what you intended, but in most use cases you will prefer the client to try reconnecting until the MQTT becomes available again.

I will will open a separate issue for this.

Thank you again for your work!
