### ISSUE TITLE
Timer 'reconnecting...' does not exist

### ISSUE THREAD

**Issue by andypotato** [kaandesu/vue-paho-mqtt#90]
This error is triggered in `onConnectionLost.ts` line 46:
```
console.timeEnd('reconnecting...');
```

However there is no previous timer named `reconnecting...`

This line should probably be removed.

**Comment by kaandesu** [comment]
hello, yes thanks for the issue, i am currently checking the previous issue and also noticed that, will publish the fix during the day.
